[package]
name = "cli_series"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
