[package]
name = "cli_series"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }
uuid = { version = "1.10.0", features = ["v4"] }
termsize = { version = "0.1.9" }
